'use client'
import { createContext, useContext, useState, useCallback, ReactNode } from 'react'

type Lang = 'en' | 'ar'

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    'nav.howItWorks': 'How It Works',
    'nav.pricing': 'Pricing',
    'nav.features': 'Features',
    'nav.hireTalent': 'Hire Talent',
    'nav.getHired': 'Get Hired',
    'nav.login': 'Login',
    'nav.dashboard': 'Dashboard',
    'nav.logout': 'Logout',
    // Hero
    'hero.tagline': 'GCC Offshore Staffing',
    'hero.title': 'Hire Trained Offshore Staff in 48 Hours',
    'hero.subtitle': 'Pre-vetted Admin, Sales & Design talent from Pakistan, managed through one clean dashboard.',
    'hero.cta1': 'Hire Talent',
    'hero.cta2': 'Get Hired',
    // How It Works
    'how.tagline': 'Simple Process',
    'how.title': 'How It Works',
    'how.step1.title': 'Register & Sign',
    'how.step1.desc': 'Create your account and sign the service agreement in under 2 minutes.',
    'how.step2.title': 'Browse Talent',
    'how.step2.desc': 'Access our curated database of pre-vetted professionals.',
    'how.step3.title': 'Hire & Manage',
    'how.step3.desc': 'Select your talent and manage everything from one dashboard.',
    // Pricing
    'pricing.tagline': 'Transparent Pricing',
    'pricing.title': 'Simple Monthly Rates',
    'pricing.aed': 'AED',
    'pricing.month': '/month',
    'pricing.adminSales': 'Admin & Sales',
    'pricing.design': '2D Design',
    'pricing.home': 'Home-Based',
    'pricing.office': 'Office-Based',
    'pricing.hiringFee': 'One-time hiring fee: 300 AED (credited to first month)',
    // Features
    'features.tagline': 'Platform Features',
    'features.title': 'Everything You Need',
    'features.f1.title': '48-Hour Hiring',
    'features.f1.desc': 'From browsing to active employee in under 48 hours.',
    'features.f2.title': 'Voice Introductions',
    'features.f2.desc': 'Hear candidates before you hire them.',
    'features.f3.title': 'Clean Dashboard',
    'features.f3.desc': 'Manage employees, billing, and requests in one place.',
    'features.f4.title': 'Bilingual Support',
    'features.f4.desc': 'Full Arabic and English interface and contracts.',
    // CTA
    'cta.title': 'Ready to Scale Your Team?',
    'cta.subtitle': 'Start hiring pre-vetted offshore talent today.',
    'cta.button': 'Get Started',
    // Footer
    'footer.company': 'VirtuHire',
    'footer.desc': 'GCC offshore staffing platform.',
    'footer.links': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.terms': 'Terms of Service',
    'footer.privacy': 'Privacy Policy',
    'footer.refund': 'Refund Policy',
    'footer.vat': 'VAT Policy',
    'footer.rights': '© 2025 VirtuHire. All rights reserved.',
    // Register
    'register.step': 'Step 1 of 7',
    'register.title': 'Create Your Account',
    'register.description': 'Join VirtuHire and start hiring trained offshore staff within 48 hours.',
    'register.individual': 'Individual',
    'register.corporate': 'Corporate',
    'register.fullName': 'Full Name',
    'register.email': 'Email Address',
    'register.phone': 'Phone Number',
    'register.password': 'Password',
    'register.companyName': 'Company Name',
    'register.vatNumber': 'VAT Number',
    'register.contactPerson': 'Contact Person',
    'register.emiratesId': 'Emirates ID (upload)',
    'register.tradeLicense': 'Trade License (upload)',
    'register.next': 'Create Account & Continue',
    'register.haveAccount': 'Already have an account? Sign in',
    'register.verificationCodeRequired': 'Verification code is required',
    // Contract
    'contract.step': 'Step 2 of 7',
    'contract.title': 'Service Agreement',
    'contract.description': 'Review and sign the VirtuHire service agreement to proceed.',
    'contract.agree': 'I have read and agree to the terms and conditions of this service agreement.',
    'contract.signature': 'Your Signature',
    'contract.clear': 'Clear',
    'contract.signHere': 'Draw your signature here',
    'contract.next': 'Sign & Continue',
    'contract.fullText': 'SERVICE AGREEMENT\n\nThis Service Agreement ("Agreement") is entered into between VirtuHire ("Provider") and the Client ("Client").\n\n1. SERVICES\nThe Provider agrees to provide offshore staffing services including recruitment, onboarding, and management of remote employees.\n\n2. PAYMENT TERMS\nThe Client agrees to pay the monthly fees as displayed during the hiring process. A one-time hiring fee of 300 AED per employee applies and is credited toward the first month.\n\n3. TERM & TERMINATION\nThis agreement is month-to-month. Either party may terminate with 30 days written notice. Services will continue until the end of the current billing cycle.\n\n4. CONFIDENTIALITY\nBoth parties agree to maintain confidentiality of all business information shared during the course of this agreement.\n\n5. EMPLOYEE BUYOUT\nThe Client may purchase a direct employment relationship with any provided employee for a fixed fee of 5,000 AED.\n\n6. LIABILITY\nThe Provider shall not be liable for any indirect, incidental, or consequential damages arising from the services provided.\n\n7. GOVERNING LAW\nThis agreement is governed by the laws of the United Arab Emirates.',
    'contract.fullTextAr': 'اتفاقية الخدمة\n\nتم إبرام اتفاقية الخدمة هذه ("الاتفاقية") بين فيرتيوهاير ("المزود") والعميل ("العميل").\n\n1. الخدمات\nيوافق المزود على تقديم خدمات التوظيف عن بعد بما في ذلك التوظيف والتدريب وإدارة الموظفين عن بعد.\n\n2. شروط الدفع\nيوافق العميل على دفع الرسوم الشهرية كما هو موضح أثناء عملية التوظيف. تطبق رسوم توظيف لمرة واحدة قدرها 300 درهم لكل موظف وتُخصم من الشهر الأول.\n\n3. المدة والإنهاء\nهذه الاتفاقية شهرية. يجوز لأي طرف الإنهاء بإشعار كتابي مدته 30 يوماً.\n\n4. السرية\nيوافق الطرفان على الحفاظ على سرية جميع المعلومات التجارية.\n\n5. شراء الموظف\nيمكن للعميل شراء علاقة توظيف مباشرة مع أي موظف مقابل رسم ثابت قدره 5,000 درهم.\n\n6. المسؤولية\nلا يتحمل المزود أي أضرار غير مباشرة أو عرضية.\n\n7. القانون الحاكم\nتخضع هذه الاتفاقية لقوانين دولة الإمارات العربية المتحدة.',
    // Payment
    'payment.step3': 'Step 3 of 7',
    'payment.paymentSetup': 'Payment Setup',
    'payment.paymentDesc': 'Add your payment method to enable billing. Your card will only be charged when you initiate a hire.',
    'payment.cardNumber': 'Card Number',
    'payment.expiryDate': 'Expiry Date',
    'payment.cvv': 'CVV',
    'payment.cardholderName': 'Cardholder Name',
    'payment.cardholderPlaceholder': 'As shown on card',
    'payment.cardHolder': 'Card Holder',
    'payment.expires': 'Expires',
    'payment.billingAddress': 'Billing Address',
    'payment.billingAddressPlaceholder': 'Street address, city',
    'payment.vatNumberOptional': 'VAT Number (optional)',
    'payment.autoBilling': 'Auto Monthly Billing',
    'payment.autoBillingDesc': 'Automatically charge your card each month',
    'payment.securePayments': 'Secured by Stripe. We never store your card details.',
    'payment.nextHiringRequest': 'Continue to Hiring',
    // Hire
    'hire.step': 'Step 4 of 7',
    'hire.title': 'Hiring Request',
    'hire.description': 'Select the category, work type, and number of employees you need.',
    'hire.categoryLabel': 'Select Category',
    'hire.categories.adminSales': 'Admin & Sales',
    'hire.categories.adminSalesDesc': 'Customer support, data entry, sales coordination',
    'hire.categories.design': '2D Design',
    'hire.categories.designDesc': 'Graphic design, branding, social media',
    'hire.workTypeLabel': 'Work Type',
    'hire.workTypes.home': 'Home-Based',
    'hire.workTypes.homeDesc': 'Employee works remotely',
    'hire.workTypes.office': 'Office-Based',
    'hire.workTypes.officeDesc': 'Employee works from our office',
    'hire.employeeCount': 'Number of Employees',
    'hire.employeeSingular': 'employee',
    'hire.employeePlural': 'employees',
    'hire.monthAbbr': 'mo',
    'hire.costSummary': 'Cost Summary',
    'hire.hiringFee': 'Hiring Fee (300 AED × employees)',
    'hire.monthlyCost': 'Monthly Cost',
    'hire.dueNow': 'Due Now',
    'hire.hiringFeeNote': 'Hiring fee is credited toward your first monthly invoice.',
    'hire.payAndBrowse': 'Pay {amount} AED & Browse Talent',
    // Talent
    'talent.step': 'Step 5 of 7',
    'talent.title': 'Discover Talent',
    'talent.description': 'Browse our pre-vetted candidates. You can shortlist up to 3 and request interviews.',
    'talent.showing': 'Showing',
    'talent.candidates': 'candidates',
    'talent.of': 'of',
    'talent.shortlisted': 'Shortlisted',
    'talent.shortlist': 'Shortlist',
    'talent.remove': 'Remove',
    'talent.requestInterview': 'Request Interview',
    'talent.interviewRequested': 'Interview Requested',
    'talent.listen': 'Listen',
    'talent.experience': 'Experience',
    'talent.skills': 'Skills',
    'talent.perMonth': '/month',
    'talent.featured': 'Featured',
    'talent.batchInfo': 'Round {current} of {total} — {remaining} candidates remaining',
    'talent.loadMore': 'Load More Candidates (200 AED)',
    'talent.proceedToConfirm': 'Proceed with Shortlisted',
    'talent.maxShortlist': 'Maximum 3 candidates can be shortlisted',
    'talent.noResults': 'No candidates found matching your criteria.',
    'talent.filterAll': 'All',
    // Confirm
    'confirm.step': 'Step 6 of 7',
    'confirm.title': 'Confirm Hiring',
    'confirm.description': 'Review your selection and confirm the hire. Your employee will be activated immediately.',
    'confirm.selectedCandidate': 'Selected Candidate',
    'confirm.additionalCandidate': 'Additional Candidate',
    'confirm.monthly': 'Monthly',
    'confirm.paymentBreakdown': 'Payment Breakdown',
    'confirm.firstMonthRate': 'First Month Rate',
    'confirm.hiringFeeCredited': 'Hiring Fee (credited)',
    'confirm.dueNow': 'Due Now',
    'confirm.savedCard': 'Payment via saved card ending ••••',
    'confirm.change': 'Change',
    'confirm.payAndConfirm': 'Pay {amount} AED & Confirm',
    'confirm.processing': 'Processing...',
    'confirm.successTitle': 'Hiring Confirmed!',
    'confirm.successMessageSingle': '{name} is now active as your employee.',
    'confirm.successMessagePlural': '{count} employees are now active.',
    'confirm.goToDashboard': 'Go to Dashboard',
    'confirm.goBack': 'Go Back',
    'confirm.loading': 'Loading...',
    'confirm.missingData': 'Missing hiring data. Please go back and try again.',
    'confirm.loadError': 'Failed to load hiring data.',
    'confirm.confirmError': 'Failed to confirm hire. Please try again.',
    // Dashboard
    'dash.title': 'Dashboard',
    'dash.overview': 'Overview',
    'dash.employees': 'Employees',
    'dash.billing': 'Billing',
    'dash.requests': 'Requests',
    'dash.support': 'Support',
    'dash.services': 'Services',
    'dash.settings': 'Settings',
    'dash.activeEmployees': 'Active Employees',
    'dash.monthlyCost': 'Monthly Cost',
    'dash.notifications': 'Notifications',
    'dash.recentActivity': 'Recent Activity',
    'dash.noEmployees': 'No active employees yet.',
    'dash.hireFirst': 'Hire Your First Employee',
    'dash.replace': 'Replace',
    'dash.replaceConfirm': 'This will end the current employee at the end of the billing cycle. Continue?',
    'dash.addEmployee': 'Add Employee',
    'dash.invoices': 'Invoices',
    'dash.paymentHistory': 'Payment History',
    'dash.noInvoices': 'No invoices yet.',
    'dash.download': 'Download',
    'dash.interviewRequests': 'Interview Requests',
    'dash.hiringProgress': 'Hiring Progress',
    'dash.noRequests': 'No active requests.',
    'dash.newTicket': 'New Ticket',
    'dash.ticketSubject': 'Subject',
    'dash.ticketMessage': 'Message',
    'dash.ticketCategory': 'Category',
    'dash.submitTicket': 'Submit Ticket',
    'dash.noTickets': 'No support tickets.',
    'dash.buyout': 'Employee Buyout',
    'dash.buyoutDesc': 'Purchase direct employment for 5,000 AED',
    'dash.buyoutFee': '5,000 AED',
    'dash.supervisor': 'Supervisor Access',
    'dash.supervisorDesc': 'View-only access for your supervisors',
    'dash.accountManager': 'Account Manager',
    'dash.cancelService': 'Cancel Service',
    'dash.cancelNotice': 'Service cancellation requires 1-month notice. Your services will end at the current billing cycle.',
    'dash.confirmCancel': 'Confirm Cancellation',
    'dash.profileDetails': 'Profile Details',
    'dash.companyDocs': 'Company Documents',
    'dash.security': 'Security',
    'dash.save': 'Save Changes',
    // Login
    'login.signIn': 'Sign In',
    'login.welcomeBack': 'Welcome back. Sign in to your account.',
    'login.email': 'Email',
    'login.emailPlaceholder': 'you@company.com',
    'login.password': 'Password',
    'login.passwordPlaceholder': '••••••••',
    'login.loginButton': 'Sign In',
    'login.loggingIn': 'Signing in...',
    'login.loginFailed': 'Invalid email or password',
    'login.dontHaveAccount': "Don't have an account? Register",
    // Verify OTP
    'verify.step': 'Email Verification',
    'verify.title': 'Verify Your Email',
    'verify.instruction': 'Enter the 6-digit code sent to {email}',
    'verify.verifyButton': 'Verify',
    'verify.verifying': 'Verifying...',
    'verify.invalidCode': 'Invalid verification code',
    'verify.successTitle': 'Email Verified!',
    'verify.successMessage': 'Your email has been verified. Redirecting...',
    // Candidate
    'candidate.title': 'Apply to VirtuHire',
    'candidate.subtitle': 'Join our talent pool and get connected with GCC clients.',
    'candidate.fullName': 'Full Name',
    'candidate.email': 'Email Address',
    'candidate.phone': 'Phone Number',
    'candidate.location': 'Location',
    'candidate.category': 'Category',
    'candidate.workPreference': 'Work Preference',
    'candidate.experience': 'Experience Summary',
    'candidate.cv': 'Upload CV',
    'candidate.voiceIntro': 'Voice Introduction (1 min, required)',
    'candidate.voiceNote': 'Record a 1-minute audio introduction about yourself.',
    'candidate.submit': 'Submit Application',
    'candidate.submitting': 'Submitting...',
    'candidate.success': 'Application Submitted!',
    'candidate.successMsg': 'Your application is under review. We will notify you once it is processed.',
    'candidate.homeRate': 'Home-based rate',
    'candidate.officeRate': 'Office-based rate',
    // Legal
    'legal.terms.title': 'Terms of Service',
    'legal.privacy.title': 'Privacy Policy',
    'legal.refund.title': 'Refund Policy',
    'legal.vat.title': 'VAT Policy',
    'legal.terms.lastUpdated': 'Last updated: March 2025',
    'legal.privacy.lastUpdated': 'Last updated: March 2025',
    'legal.refund.lastUpdated': 'Last updated: March 2025',
    'legal.vat.lastUpdated': 'Last updated: March 2025',
    'legal.terms.section1.title': '1. Acceptance of Terms',
    'legal.terms.section1.content': 'By accessing or using VirtuHire, you agree to be bound by these Terms of Service.',
    'legal.terms.section2.title': '2. Services',
    'legal.terms.section2.content': 'VirtuHire provides offshore staffing services connecting GCC businesses with trained professionals.',
    'legal.terms.section3.title': '3. User Accounts',
    'legal.terms.section3.content': 'You are responsible for maintaining the confidentiality of your account credentials.',
    'legal.terms.section4.title': '4. Payment Terms',
    'legal.terms.section4.content': 'All fees are in AED. Monthly billing occurs automatically unless cancelled.',
    'legal.terms.section5.title': '5. Termination',
    'legal.terms.section5.content': 'Either party may terminate with 30 days written notice. Services end at billing cycle completion.',
    'legal.terms.section6.title': '6. Limitation of Liability',
    'legal.terms.section6.content': 'VirtuHire is not liable for indirect damages arising from the use of our services.',
    'legal.terms.section7.title': '7. Governing Law',
    'legal.terms.section7.content': 'These terms are governed by the laws of the United Arab Emirates.',
    'legal.privacy.section1.title': '1. Information We Collect',
    'legal.privacy.section1.content': 'We collect information you provide during registration, including name, email, phone, and business documents.',
    'legal.privacy.section2.title': '2. How We Use Information',
    'legal.privacy.section2.content': 'Your information is used to provide staffing services, process payments, and communicate updates.',
    'legal.privacy.section3.title': '3. Data Security',
    'legal.privacy.section3.content': 'We implement industry-standard security measures to protect your personal and business information.',
    'legal.privacy.section4.title': '4. Third-Party Sharing',
    'legal.privacy.section4.content': 'We do not sell your data. Information may be shared with payment processors (Stripe) as necessary.',
    'legal.privacy.section5.title': '5. Data Retention',
    'legal.privacy.section5.content': 'We retain your data for the duration of your account and as required by law.',
    'legal.privacy.section6.title': '6. Contact',
    'legal.privacy.section6.content': 'For privacy inquiries, contact us at privacy@virtuhire.ae.',
    'legal.refund.section1.title': '1. Hiring Fee',
    'legal.refund.section1.content': 'The 300 AED hiring fee is non-refundable but is credited toward your first month.',
    'legal.refund.section2.title': '2. Monthly Fees',
    'legal.refund.section2.content': 'Monthly fees are non-refundable once the billing cycle has begun.',
    'legal.refund.section3.title': '3. Extra Candidate Batches',
    'legal.refund.section3.content': 'The 200 AED batch fee is non-refundable once candidates have been revealed.',
    'legal.refund.section4.title': '4. Disputes',
    'legal.refund.section4.content': 'For billing disputes, please contact billing@virtuhire.ae within 7 days.',
    'legal.vat.section1.title': '1. VAT Registration',
    'legal.vat.section1.content': 'VirtuHire is registered for VAT in the United Arab Emirates.',
    'legal.vat.section2.title': '2. VAT on Services',
    'legal.vat.section2.content': 'All prices displayed are exclusive of VAT unless stated otherwise.',
    'legal.vat.section3.title': '3. Tax Invoices',
    'legal.vat.section3.content': 'Tax-compliant invoices are generated automatically and available in your dashboard.',
    'legal.vat.section4.title': '4. Reverse Charge',
    'legal.vat.section4.content': 'For clients outside the UAE, reverse charge mechanism may apply.',
  },
  ar: {
    'nav.howItWorks': 'كيف يعمل',
    'nav.pricing': 'الأسعار',
    'nav.features': 'المميزات',
    'nav.hireTalent': 'وظّف',
    'nav.getHired': 'احصل على وظيفة',
    'nav.login': 'تسجيل الدخول',
    'nav.dashboard': 'لوحة التحكم',
    'nav.logout': 'تسجيل الخروج',
    'hero.tagline': 'التوظيف عن بعد لدول الخليج',
    'hero.title': 'وظّف كوادر مدربة خلال 48 ساعة',
    'hero.subtitle': 'كوادر إدارية ومبيعات وتصميم مُعتمدة من باكستان، تُدار من لوحة تحكم واحدة.',
    'hero.cta1': 'وظّف الآن',
    'hero.cta2': 'احصل على وظيفة',
    'how.tagline': 'عملية بسيطة',
    'how.title': 'كيف يعمل',
    'how.step1.title': 'سجّل ووقّع',
    'how.step1.desc': 'أنشئ حسابك ووقّع اتفاقية الخدمة في أقل من دقيقتين.',
    'how.step2.title': 'تصفح المواهب',
    'how.step2.desc': 'اطّلع على قاعدة بيانات المرشحين المُعتمدين.',
    'how.step3.title': 'وظّف وأدِر',
    'how.step3.desc': 'اختر موظفك وأدِر كل شيء من لوحة تحكم واحدة.',
    'pricing.tagline': 'أسعار شفافة',
    'pricing.title': 'أسعار شهرية بسيطة',
    'pricing.aed': 'درهم',
    'pricing.month': '/شهر',
    'pricing.adminSales': 'إدارة ومبيعات',
    'pricing.design': 'تصميم ثنائي الأبعاد',
    'pricing.home': 'عن بعد',
    'pricing.office': 'من المكتب',
    'pricing.hiringFee': 'رسوم توظيف لمرة واحدة: 300 درهم (تُخصم من الشهر الأول)',
    'features.tagline': 'مميزات المنصة',
    'features.title': 'كل ما تحتاجه',
    'features.f1.title': 'توظيف خلال 48 ساعة',
    'features.f1.desc': 'من التصفح إلى موظف نشط في أقل من 48 ساعة.',
    'features.f2.title': 'تعريف صوتي',
    'features.f2.desc': 'استمع إلى المرشحين قبل التوظيف.',
    'features.f3.title': 'لوحة تحكم نظيفة',
    'features.f3.desc': 'أدِر الموظفين والفواتير والطلبات في مكان واحد.',
    'features.f4.title': 'دعم ثنائي اللغة',
    'features.f4.desc': 'واجهة وعقود كاملة بالعربية والإنجليزية.',
    'cta.title': 'مستعد لتوسيع فريقك؟',
    'cta.subtitle': 'ابدأ بتوظيف كوادر مُعتمدة اليوم.',
    'cta.button': 'ابدأ الآن',
    'footer.company': 'فيرتيوهاير',
    'footer.desc': 'منصة توظيف عن بعد لدول الخليج.',
    'footer.links': 'روابط سريعة',
    'footer.legal': 'قانوني',
    'footer.terms': 'شروط الخدمة',
    'footer.privacy': 'سياسة الخصوصية',
    'footer.refund': 'سياسة الاسترداد',
    'footer.vat': 'سياسة الضريبة',
    'footer.rights': '© 2025 فيرتيوهاير. جميع الحقوق محفوظة.',
    'register.step': 'الخطوة 1 من 7',
    'register.title': 'أنشئ حسابك',
    'register.description': 'انضم إلى فيرتيوهاير وابدأ بتوظيف كوادر مدربة خلال 48 ساعة.',
    'register.individual': 'فردي',
    'register.corporate': 'شركة',
    'register.fullName': 'الاسم الكامل',
    'register.email': 'البريد الإلكتروني',
    'register.phone': 'رقم الهاتف',
    'register.password': 'كلمة المرور',
    'register.companyName': 'اسم الشركة',
    'register.vatNumber': 'الرقم الضريبي',
    'register.contactPerson': 'الشخص المسؤول',
    'register.emiratesId': 'الهوية الإماراتية (رفع)',
    'register.tradeLicense': 'الرخصة التجارية (رفع)',
    'register.next': 'إنشاء الحساب والمتابعة',
    'register.haveAccount': 'لديك حساب؟ سجّل الدخول',
    'register.verificationCodeRequired': 'رمز التحقق مطلوب',
    'contract.step': 'الخطوة 2 من 7',
    'contract.title': 'اتفاقية الخدمة',
    'contract.description': 'راجع ووقّع اتفاقية خدمة فيرتيوهاير للمتابعة.',
    'contract.agree': 'لقد قرأت وأوافق على شروط وأحكام اتفاقية الخدمة هذه.',
    'contract.signature': 'توقيعك',
    'contract.clear': 'مسح',
    'contract.signHere': 'ارسم توقيعك هنا',
    'contract.next': 'التوقيع والمتابعة',
    'payment.step3': 'الخطوة 3 من 7',
    'payment.paymentSetup': 'إعداد الدفع',
    'payment.paymentDesc': 'أضف طريقة الدفع لتفعيل الفوترة. لن يتم خصم أي مبلغ حتى تبدأ بالتوظيف.',
    'payment.cardNumber': 'رقم البطاقة',
    'payment.expiryDate': 'تاريخ الانتهاء',
    'payment.cvv': 'CVV',
    'payment.cardholderName': 'اسم حامل البطاقة',
    'payment.cardholderPlaceholder': 'كما هو مكتوب على البطاقة',
    'payment.cardHolder': 'حامل البطاقة',
    'payment.expires': 'ينتهي',
    'payment.billingAddress': 'عنوان الفوترة',
    'payment.billingAddressPlaceholder': 'العنوان، المدينة',
    'payment.vatNumberOptional': 'الرقم الضريبي (اختياري)',
    'payment.autoBilling': 'فوترة تلقائية شهرية',
    'payment.autoBillingDesc': 'خصم تلقائي من بطاقتك كل شهر',
    'payment.securePayments': 'مؤمّن بواسطة Stripe. لا نخزن بيانات بطاقتك.',
    'payment.nextHiringRequest': 'المتابعة للتوظيف',
    'hire.step': 'الخطوة 4 من 7',
    'hire.title': 'طلب توظيف',
    'hire.description': 'اختر الفئة ونوع العمل وعدد الموظفين المطلوبين.',
    'hire.categoryLabel': 'اختر الفئة',
    'hire.categories.adminSales': 'إدارة ومبيعات',
    'hire.categories.adminSalesDesc': 'خدمة العملاء، إدخال البيانات، تنسيق المبيعات',
    'hire.categories.design': 'تصميم ثنائي الأبعاد',
    'hire.categories.designDesc': 'تصميم جرافيك، هوية بصرية، سوشيال ميديا',
    'hire.workTypeLabel': 'نوع العمل',
    'hire.workTypes.home': 'عن بعد',
    'hire.workTypes.homeDesc': 'الموظف يعمل من المنزل',
    'hire.workTypes.office': 'من المكتب',
    'hire.workTypes.officeDesc': 'الموظف يعمل من مكتبنا',
    'hire.employeeCount': 'عدد الموظفين',
    'hire.employeeSingular': 'موظف',
    'hire.employeePlural': 'موظفين',
    'hire.monthAbbr': 'شهر',
    'hire.costSummary': 'ملخص التكلفة',
    'hire.hiringFee': 'رسوم التوظيف (300 درهم × موظف)',
    'hire.monthlyCost': 'التكلفة الشهرية',
    'hire.dueNow': 'المستحق الآن',
    'hire.hiringFeeNote': 'رسوم التوظيف تُخصم من فاتورتك الشهرية الأولى.',
    'hire.payAndBrowse': 'ادفع {amount} درهم وتصفح المواهب',
    'talent.step': 'الخطوة 5 من 7',
    'talent.title': 'اكتشف المواهب',
    'talent.description': 'تصفح المرشحين المُعتمدين. يمكنك اختيار 3 وطلب مقابلات.',
    'talent.showing': 'عرض',
    'talent.candidates': 'مرشح',
    'talent.of': 'من',
    'talent.shortlisted': 'في القائمة المختصرة',
    'talent.shortlist': 'اختيار',
    'talent.remove': 'إزالة',
    'talent.requestInterview': 'طلب مقابلة',
    'talent.interviewRequested': 'تم طلب المقابلة',
    'talent.listen': 'استمع',
    'talent.experience': 'الخبرة',
    'talent.skills': 'المهارات',
    'talent.perMonth': '/شهر',
    'talent.featured': 'مميز',
    'talent.batchInfo': 'الجولة {current} من {total} — {remaining} مرشح متبقي',
    'talent.loadMore': 'تحميل المزيد (200 درهم)',
    'talent.proceedToConfirm': 'المتابعة مع المختارين',
    'talent.maxShortlist': 'يمكنك اختيار 3 مرشحين كحد أقصى',
    'talent.noResults': 'لم يتم العثور على مرشحين.',
    'talent.filterAll': 'الكل',
    'confirm.step': 'الخطوة 6 من 7',
    'confirm.title': 'تأكيد التوظيف',
    'confirm.description': 'راجع اختيارك وأكّد التوظيف. سيتم تفعيل موظفك فوراً.',
    'confirm.selectedCandidate': 'المرشح المختار',
    'confirm.additionalCandidate': 'مرشح إضافي',
    'confirm.monthly': 'شهرياً',
    'confirm.paymentBreakdown': 'تفصيل الدفع',
    'confirm.firstMonthRate': 'تكلفة الشهر الأول',
    'confirm.hiringFeeCredited': 'رسوم التوظيف (مخصومة)',
    'confirm.dueNow': 'المستحق الآن',
    'confirm.savedCard': 'الدفع عبر البطاقة المحفوظة ••••',
    'confirm.change': 'تغيير',
    'confirm.payAndConfirm': 'ادفع {amount} درهم وأكّد',
    'confirm.processing': 'جاري المعالجة...',
    'confirm.successTitle': 'تم تأكيد التوظيف!',
    'confirm.successMessageSingle': '{name} أصبح الآن موظفك النشط.',
    'confirm.successMessagePlural': 'تم تفعيل {count} موظفين.',
    'confirm.goToDashboard': 'الذهاب للوحة التحكم',
    'confirm.goBack': 'رجوع',
    'confirm.loading': 'جاري التحميل...',
    'confirm.missingData': 'بيانات التوظيف مفقودة.',
    'confirm.loadError': 'فشل تحميل البيانات.',
    'confirm.confirmError': 'فشل التأكيد.',
    'dash.title': 'لوحة التحكم',
    'dash.overview': 'نظرة عامة',
    'dash.employees': 'الموظفون',
    'dash.billing': 'الفواتير',
    'dash.requests': 'الطلبات',
    'dash.support': 'الدعم',
    'dash.services': 'خدمات إضافية',
    'dash.settings': 'الإعدادات',
    'dash.activeEmployees': 'الموظفون النشطون',
    'dash.monthlyCost': 'التكلفة الشهرية',
    'dash.notifications': 'الإشعارات',
    'dash.recentActivity': 'النشاط الأخير',
    'dash.noEmployees': 'لا يوجد موظفون نشطون.',
    'dash.hireFirst': 'وظّف أول موظف',
    'dash.replace': 'استبدال',
    'dash.replaceConfirm': 'سيتم إنهاء الموظف الحالي في نهاية دورة الفوترة. متابعة؟',
    'dash.addEmployee': 'إضافة موظف',
    'dash.invoices': 'الفواتير',
    'dash.paymentHistory': 'سجل المدفوعات',
    'dash.noInvoices': 'لا توجد فواتير.',
    'dash.download': 'تحميل',
    'dash.interviewRequests': 'طلبات المقابلات',
    'dash.hiringProgress': 'تقدم التوظيف',
    'dash.noRequests': 'لا توجد طلبات نشطة.',
    'dash.newTicket': 'تذكرة جديدة',
    'dash.ticketSubject': 'الموضوع',
    'dash.ticketMessage': 'الرسالة',
    'dash.ticketCategory': 'الفئة',
    'dash.submitTicket': 'إرسال التذكرة',
    'dash.noTickets': 'لا توجد تذاكر دعم.',
    'dash.buyout': 'شراء الموظف',
    'dash.buyoutDesc': 'شراء علاقة توظيف مباشرة مقابل 5,000 درهم',
    'dash.buyoutFee': '5,000 درهم',
    'dash.supervisor': 'وصول المشرف',
    'dash.supervisorDesc': 'وصول للعرض فقط للمشرفين',
    'dash.accountManager': 'مدير الحساب',
    'dash.cancelService': 'إلغاء الخدمة',
    'dash.cancelNotice': 'يتطلب الإلغاء إشعار مدته شهر واحد.',
    'dash.confirmCancel': 'تأكيد الإلغاء',
    'dash.profileDetails': 'تفاصيل الملف',
    'dash.companyDocs': 'مستندات الشركة',
    'dash.security': 'الأمان',
    'dash.save': 'حفظ التغييرات',
    'login.signIn': 'تسجيل الدخول',
    'login.welcomeBack': 'مرحباً بعودتك. سجّل دخولك.',
    'login.email': 'البريد الإلكتروني',
    'login.emailPlaceholder': 'you@company.com',
    'login.password': 'كلمة المرور',
    'login.passwordPlaceholder': '••••••••',
    'login.loginButton': 'تسجيل الدخول',
    'login.loggingIn': 'جاري التسجيل...',
    'login.loginFailed': 'بريد إلكتروني أو كلمة مرور غير صحيحة',
    'login.dontHaveAccount': 'ليس لديك حساب؟ سجّل',
    'verify.step': 'التحقق من البريد',
    'verify.title': 'تحقق من بريدك',
    'verify.instruction': 'أدخل الرمز المكون من 6 أرقام المرسل إلى {email}',
    'verify.verifyButton': 'تحقق',
    'verify.verifying': 'جاري التحقق...',
    'verify.invalidCode': 'رمز تحقق غير صالح',
    'verify.successTitle': 'تم التحقق!',
    'verify.successMessage': 'تم التحقق من بريدك الإلكتروني. جاري التحويل...',
    'candidate.title': 'التقدم لفيرتيوهاير',
    'candidate.subtitle': 'انضم إلى قاعدة المواهب لدينا وتواصل مع عملاء الخليج.',
    'candidate.fullName': 'الاسم الكامل',
    'candidate.email': 'البريد الإلكتروني',
    'candidate.phone': 'رقم الهاتف',
    'candidate.location': 'الموقع',
    'candidate.category': 'الفئة',
    'candidate.workPreference': 'تفضيل العمل',
    'candidate.experience': 'ملخص الخبرة',
    'candidate.cv': 'رفع السيرة الذاتية',
    'candidate.voiceIntro': 'تعريف صوتي (دقيقة واحدة، مطلوب)',
    'candidate.voiceNote': 'سجّل تعريفاً صوتياً عن نفسك مدته دقيقة واحدة.',
    'candidate.submit': 'إرسال الطلب',
    'candidate.submitting': 'جاري الإرسال...',
    'candidate.success': 'تم إرسال الطلب!',
    'candidate.successMsg': 'طلبك قيد المراجعة. سنُعلمك حال معالجته.',
    'candidate.homeRate': 'راتب العمل من المنزل',
    'candidate.officeRate': 'راتب العمل من المكتب',
    'legal.terms.title': 'شروط الخدمة',
    'legal.privacy.title': 'سياسة الخصوصية',
    'legal.refund.title': 'سياسة الاسترداد',
    'legal.vat.title': 'سياسة الضريبة',
    'legal.terms.lastUpdated': 'آخر تحديث: مارس 2025',
    'legal.privacy.lastUpdated': 'آخر تحديث: مارس 2025',
    'legal.refund.lastUpdated': 'آخر تحديث: مارس 2025',
    'legal.vat.lastUpdated': 'آخر تحديث: مارس 2025',
    'legal.terms.section1.title': '1. قبول الشروط',
    'legal.terms.section1.content': 'باستخدامك فيرتيوهاير، توافق على الالتزام بهذه الشروط.',
    'legal.terms.section2.title': '2. الخدمات',
    'legal.terms.section2.content': 'توفر فيرتيوهاير خدمات التوظيف عن بعد لربط الشركات الخليجية بالمحترفين المدربين.',
    'legal.terms.section3.title': '3. حسابات المستخدمين',
    'legal.terms.section3.content': 'أنت مسؤول عن الحفاظ على سرية بيانات حسابك.',
    'legal.terms.section4.title': '4. شروط الدفع',
    'legal.terms.section4.content': 'جميع الرسوم بالدرهم الإماراتي. الفوترة الشهرية تلقائية.',
    'legal.terms.section5.title': '5. الإنهاء',
    'legal.terms.section5.content': 'يمكن لأي طرف الإنهاء بإشعار كتابي مدته 30 يوماً.',
    'legal.terms.section6.title': '6. حدود المسؤولية',
    'legal.terms.section6.content': 'فيرتيوهاير غير مسؤولة عن الأضرار غير المباشرة.',
    'legal.terms.section7.title': '7. القانون الحاكم',
    'legal.terms.section7.content': 'تخضع هذه الشروط لقوانين دولة الإمارات.',
    'legal.privacy.section1.title': '1. المعلومات التي نجمعها',
    'legal.privacy.section1.content': 'نجمع المعلومات التي تقدمها أثناء التسجيل.',
    'legal.privacy.section2.title': '2. كيف نستخدم المعلومات',
    'legal.privacy.section2.content': 'نستخدم معلوماتك لتقديم خدمات التوظيف ومعالجة المدفوعات.',
    'legal.privacy.section3.title': '3. أمن البيانات',
    'legal.privacy.section3.content': 'نطبق معايير أمان صناعية لحماية معلوماتك.',
    'legal.privacy.section4.title': '4. مشاركة مع أطراف ثالثة',
    'legal.privacy.section4.content': 'لا نبيع بياناتك. قد نشاركها مع معالجي الدفع.',
    'legal.privacy.section5.title': '5. الاحتفاظ بالبيانات',
    'legal.privacy.section5.content': 'نحتفظ ببياناتك طوال مدة حسابك وحسب القانون.',
    'legal.privacy.section6.title': '6. التواصل',
    'legal.privacy.section6.content': 'للاستفسارات: privacy@virtuhire.ae',
    'legal.refund.section1.title': '1. رسوم التوظيف',
    'legal.refund.section1.content': 'رسوم التوظيف 300 درهم غير قابلة للاسترداد لكنها تُخصم من الشهر الأول.',
    'legal.refund.section2.title': '2. الرسوم الشهرية',
    'legal.refund.section2.content': 'الرسوم الشهرية غير قابلة للاسترداد بعد بدء دورة الفوترة.',
    'legal.refund.section3.title': '3. دفعات إضافية',
    'legal.refund.section3.content': 'رسوم الدفعة الإضافية 200 درهم غير قابلة للاسترداد.',
    'legal.refund.section4.title': '4. النزاعات',
    'legal.refund.section4.content': 'للنزاعات: billing@virtuhire.ae خلال 7 أيام.',
    'legal.vat.section1.title': '1. التسجيل الضريبي',
    'legal.vat.section1.content': 'فيرتيوهاير مسجلة ضريبياً في الإمارات.',
    'legal.vat.section2.title': '2. الضريبة على الخدمات',
    'legal.vat.section2.content': 'الأسعار المعروضة لا تشمل الضريبة ما لم يُذكر خلاف ذلك.',
    'legal.vat.section3.title': '3. الفواتير الضريبية',
    'legal.vat.section3.content': 'تُنشأ فواتير ضريبية تلقائياً وتتوفر في لوحة التحكم.',
    'legal.vat.section4.title': '4. الاحتساب العكسي',
    'legal.vat.section4.content': 'للعملاء خارج الإمارات قد يُطبق الاحتساب العكسي.',
    'contract.fullText': 'اتفاقية الخدمة\n\nتم إبرام اتفاقية الخدمة هذه بين فيرتيوهاير والعميل.\n\n1. الخدمات\nيوافق المزود على تقديم خدمات التوظيف عن بعد.\n\n2. شروط الدفع\nيوافق العميل على دفع الرسوم الشهرية. رسوم توظيف 300 درهم تُخصم من الشهر الأول.\n\n3. المدة والإنهاء\nاتفاقية شهرية. إشعار 30 يوماً للإنهاء.\n\n4. السرية\nيوافق الطرفان على الحفاظ على السرية.\n\n5. شراء الموظف\nيمكن شراء توظيف مباشر مقابل 5,000 درهم.\n\n6. المسؤولية\nلا يتحمل المزود أضراراً غير مباشرة.\n\n7. القانون الحاكم\nقوانين دولة الإمارات.',
    'contract.fullTextAr': 'اتفاقية الخدمة\n\nتم إبرام اتفاقية الخدمة هذه بين فيرتيوهاير والعميل.\n\n1. الخدمات\nيوافق المزود على تقديم خدمات التوظيف عن بعد.\n\n2. شروط الدفع\nيوافق العميل على دفع الرسوم الشهرية. رسوم توظيف 300 درهم تُخصم من الشهر الأول.\n\n3. المدة والإنهاء\nاتفاقية شهرية. إشعار 30 يوماً للإنهاء.\n\n4. السرية\nيوافق الطرفان على الحفاظ على السرية.\n\n5. شراء الموظف\nيمكن شراء توظيف مباشر مقابل 5,000 درهم.\n\n6. المسؤولية\nلا يتحمل المزود أضراراً غير مباشرة.\n\n7. القانون الحاكم\nقوانين دولة الإمارات.',
  },
}

interface LangContextType {
  lang: Lang
  isRTL: boolean
  setLang: (l: Lang) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LangContextType>({
  lang: 'en', isRTL: false, setLang: () => {}, t: (k) => k,
})

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')
  const isRTL = lang === 'ar'

  const setLang = useCallback((l: Lang) => {
    setLangState(l)
    if (typeof document !== 'undefined') {
      document.documentElement.dir = l === 'ar' ? 'rtl' : 'ltr'
      document.documentElement.lang = l
    }
  }, [])

  const t = useCallback((key: string) => {
    return translations[lang][key] || translations['en'][key] || key
  }, [lang])

  return (
    <LanguageContext.Provider value={{ lang, isRTL, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export const useLanguage = () => useContext(LanguageContext)
